pipeline {
    agent any

    environment {
        SNOWSQL_PATH = 'C:\\Program Files\\Program Files\\SnowSQL\\snowsql.exe'  // Path to snowsql.exe
        SNOWSQL_CONFIG = 'C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\SQL_SC_TEST\\.snowsql\\config' // Path to SnowSQL config file
        SNOWFLAKE_ACCOUNT = 'mg05545.eu-west-1'            // Snowflake account
        SNOWFLAKE_USER = 'MRAJAMANI'              // Snowflake username
        SNOWFLAKE_PASSWORD = 'Muruga@20608'          // Snowflake password
        SNOWFLAKE_DATABASE = 'POC_CICD_PROD'          // Snowflake database
        SNOWFLAKE_SCHEMA = 'SH_PROD'              // Snowflake schema
        SNOWFLAKE_WAREHOUSE = 'POC_ITIM_PERIASAMY'        // Snowflake warehouse
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/manjunathbabur/sql_dy_snowsql.git'
            }
        }

        stage('Validate SnowSQL') {
            steps {
                bat """
                %SNOWSQL_PATH% --version --config %SNOWSQL_CONFIG%
                """
            }
        }

        stage('Deploy SQL to Snowflake') {
            steps {
                bat """
                %SNOWSQL_PATH% --config %SNOWSQL_CONFIG% ^
                               -a %SNOWFLAKE_ACCOUNT% ^
                               -u %SNOWFLAKE_USER% ^
                               -p %SNOWFLAKE_PASSWORD% ^
                               -d %SNOWFLAKE_DATABASE% ^
                               -s %SNOWFLAKE_SCHEMA% ^
                               -w %SNOWFLAKE_WAREHOUSE% ^
                               -f sql\\create_table.sql
                """
            }
        }
    }
}
