pipeline {
    agent any

    environment {
        SNOWSQL_PATH = "\"C:\\Program Files\\SnowSQL\\snowsql.exe\""
        SNOWSQL_CONFIG = "C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\SQL_SC_TEST\\.snowsql\\config"
        SNOWFLAKE_ACCOUNT = 'mg05545.eu-west-1'
        SNOWFLAKE_USER = 'MRAJAMANI'
        SNOWFLAKE_PASSWORD = 'Muruga@20608'
        SNOWFLAKE_DATABASE = 'POC_CICD_PROD'
        SNOWFLAKE_SCHEMA = 'SH_PROD'
        SNOWFLAKE_WAREHOUSE = 'POC_ITIM_PERIASAMY'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/manjunathbabur/sql_dy_snowsql.git'
            }
        }

        stage('Validate SnowSQL') {
            steps {
                bat """
                %SNOWSQL_PATH% --config %SNOWSQL_CONFIG% --version
                """
            }
        }

        stage('Deploy SQL to Snowflake') {
            steps {
                bat """
                %SNOWSQL_PATH% --config %SNOWSQL_CONFIG% ^
                               -a %SNOWFLAKE_ACCOUNT% ^
                               -u %SNOWFLAKE_USER% ^
                               -p %SNOWFLAKE_PASSWORD% ^
                               -d %SNOWFLAKE_DATABASE% ^
                               -s %SNOWFLAKE_SCHEMA% ^
                               -w %SNOWFLAKE_WAREHOUSE% ^
                               -f sql\\create_table.sql
                """
            }
        }
    }
}
